@startuml DiagramaClasesAmpliado

title Cafetería — Diagrama de Clases Ampliado

package "Presupuesto" {
  class Presupuesto {
  }

  class ObjetivoCostoReceta {
  }
}

package "Proveedor" {
  class Proveedor {
  }

  class OrdenCompra {
  }

  class ItemCompra {
  }

  class ContratoProveedor {
  }

  Proveedor -- OrdenCompra : recibe
  OrdenCompra *-- ItemCompra : contiene
  Proveedor -- ContratoProveedor : firma
}


package "Inventario" {
  class Producto {
  }

  class Categoria {
  }

  class MovimientoStock {
  }

  class Almacen {
  }

  class Lote {
  }

  Categoria o-- Producto : clasifica
  Producto -- MovimientoStock : mueve
  Almacen -- Lote : contiene
  Producto -- Lote : se agrupa en
}

package "Receta" {
  class Receta {
  }

  class RecetaIngrediente {
  }

  Receta -- RecetaIngrediente : incluye
}

package "Menu" {
  class Menu {
  }

  class SeccionMenu {
  }

  class MenuItem {
  }

  Menu -- SeccionMenu : organiza
  SeccionMenu -- MenuItem : contiene
}

Proveedor.Proveedor -- Inventario.Producto : suministra
Proveedor.ItemCompra -- Inventario.Producto : compra

Receta.RecetaIngrediente -- Inventario.Producto : usa

Menu.MenuItem -- Receta.Receta : referencia

Presupuesto.Presupuesto -- Proveedor.OrdenCompra : limita
Presupuesto.ObjetivoCostoReceta -- Receta.Receta : se ajusta a

@enduml